name: Publish on PyPI

on: 
  push:
    branches: 
      - "main"
      - "publishing-workflow"
  release:
    types: [created]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install the latest version of uv and set the python version
      uses: astral-sh/setup-uv@v6.7.0
      with:
        python-version: "3.12"

    - name: Build wheel
      run: |
        uv build

    - name: Upload build for publishing
      uses: actions/upload-artifact@v4
      with:
        name: parxyval_release
        if-no-files-found: error
        retention-days: 1
        path: dist/*

  pypi:
    name: Upload release to PyPI
    # if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: build
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6.7.0
        # if: github.event_name == 'release'
        with:
          enable-cache: false
          ignore-empty-workdir: true
          python-version: "3.12"

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: parxyval_release
          path: dist

      - name: Publish package distributions to PyPI
        # if: github.event_name == 'release'
        run: uv publish